schema_version = "1.0.0"

blender_version_min = "4.2.0"
id = "gesture_helper"
license = ["SPDX:GPL-2.0-or-later", ]
maintainer = "小萌新"
name = "Gesture Helper"
tagline = "Gesture Helper, which allows you to quickly use gestures to run the blender operator or change properties"
type = "add-on"
version = "2.0.1"
tags = ["3D View", "User Interface"]
