data = {
    'Set the index value of the index and move the item through the index of the current item.': '通过当前项的index,来设置索引的index值,以及移动项',
    'Gesture Assistant, which allows for quick execution of Blender operators or modification of properties using gestures.': '手势助手,可以快速的使用手势运行blender 操作符或是更改属性',
    'Expand Boolean Property': '展开布尔属性',
    'AIGODLIKE': '幻之境',
    'root': '根',
    'same': '同级',
    'child': '子级',
    'Not Select Gesture': '需要选中一个手势',
    'Auto-generated Boolean Property': '自动生成的布尔属性',
    'Add Expand Property': '添加展开属性',
    'Split Coefficient': '拆分系数',
    'Add Default Value for Boolean Property': '添加布尔属性的默认值',
    'Display Enable/Disable Button': '显示 启用/禁用 按钮',
    'Display on the Left': '显示在左侧',
    'Font Size': '文字大小',
    'Text Size for GPU Rendering': 'Gpu绘制的文字大小',
    'Corner Radius Size': '圆角大小',
    'Corner Radius Size for GPU Rendering': 'Gpu绘制的圆角大小',
    'Margin Size for GPU Rendering': 'Gpu绘制的Margin大小',
    'Line Width Size for GPU Rendering': 'Gpu绘制的线宽大小',
    'Line Width': '线宽',
    'Default Background Color': '背景默认颜色',
    'Active Background Color': '背景活动颜色',
    'Default Text Color': '文字默认颜色',
    'Active Text Color': '文字活动颜色',
    'Mouse Trail Color': '鼠标轨迹颜色',
    'Gesture Trail Color': '手势轨迹颜色',
    'Debug Mode': 'Debug模式',
    'Debug Shortcut': 'Debug快捷键',
    'Debug Drawing in GPU Mode': 'Debug绘制Gpu模式',
    'Auto-Update Action Properties': '自动更新操作属性',
    'Move Element: the entire element requires only the move operator to be available': '移动元素 整个元素需要只有移动操作符可用',
    'Automatic Backup': '自动备份',
    "Automatically save data every time the plugin is deactivated, to avoid data loss due to accidental operations. The automatic save path is in the 'auto_backups' folder of the plugin's path": "在每次注销插件时自动保存数据,避免误操作导致数据丢失, 自动保存的路径在插件路径的 'auto_backups' 文件夹",
    'Automatically handle conflicting shortcuts when setting key mappings': '设置快捷键映射时自动处理冲突快捷键',
    'Display Gesture Item Shortcuts': '显示手势项快捷键',
    'Gesture': '手势',
    'Please select or add a gesture element': '请 选择或添加 一个手势元素',
    'Add Element Relationship': '添加元素关系',
    'Add Item': '添加项',
    "Cannot add a child to 'Operator'": "无法为 '操作符' 添加子级",
    'Please add or select a gesture': '请添加或选择一个手势',
    'Exit': '退出',
    'Gesture Index': '手势索引',
    'Enable Gesture': '启用手势',
    'Enable or disable the entire system, mainly the keymap': '启用禁用整个系统,主要是keymap',
    'Display Panel': '显示面板',
    'Active Item Object Type': '活动项物体类型',
    'object mode': '物体模式',
    'grid selection mode': '网格选择模式',
    'vertices only': '仅顶点',
    'edges only': '仅边',
    'faces only': '仅面',
    'vertices & faces only': '仅 顶点&面',
    'edges & faces only': '仅 边&面',
    'vertices & edges only': '仅 顶点&边',
    'vertices & edges & faces': '顶点&边&面',
    'region type': '区域类型',
    'the type of space': '空间类型',
    'other': '其它',
    'the object s is selected': '选择了物体的',
    'select the structure': '选择结构',
    'subgesture': '子手势',
    'operator': '操作符',
    "Set the index value of the index based on the current item's index and move the item": '通过当前项的index,来设置索引的index值,以及移动项',
    'index': '索引',
    'Enable this gesture': '启用此手势',
    'Enable or disable this gesture, primarily for keymap updates': '启用禁用此手势,主要是keymap的更新',
    'Keybinding data used for storing shortcuts': '用来存快捷键的键位数据',
    'Region used to store available shortcuts': '用来存快捷键可用的区域',
    'Key Update is called by {}': 'Key Update 被 {} 调用',
    'Add gesture': '添加手势',
    'Delete gestures': '删除手势',
    'Sort gestures': '排序手势',
    'Copy gestures': '复制手势',
    'This is a gesture': '这是一个手势',
    'exception': '例外',
    "Set the index value of the index based on the current item's index and move the item": '通过当前项的index,来设置索引的index值,以及移动项',
    "relationship": '关系',
    "type": '类型',
    "selection structure type": '选择结构类型',
    "direction": '方向',
    "enable": '启用',
    "displays the children": '显示子级',
    "poll expression": 'poll表达式',
    "Operator bl_idname": '操作符 bl_idname',
    "Default to add a monkey head": '默认为添加猴头',
    "operator context": '操作符上下文',
    "operator properties": '操作符属性',
    "Updates from attributes": '从属性更新',
    "Update to Properties": '更新到属性',
    "Select the structure": '选择结构',
    "Delete the gesture item": '删除手势项',
    "Add a gesture item": '添加手势项',
    "Move the gesture item": '移动手势项',
    "Sort gesture items": '排序手势项',
    "Duplicate gesture items": '复制手势项',
    "Child elements": '子级元素',
    "Pop up gesture window": '弹出手势窗口',
    "set poll expression": '设置条件表达式',
    "Is to set the poll for an item": '是设置一个项的poll',
    "negation": '取反',
    "condition": '条件',
    "Grammatical explanations": '语法解释',
    "Can use Python logical operators or expressions": '可使用Python逻辑运算符或表达式',
    "x and y boolean 'and' - If x is False, x and y return the value of x, otherwise, return the computed value of y": 'x and y 布尔"与" - 如果 x 为 False，x and y 返回 x 的值，否则返回 y 的计算值',
    "x or y boolean 'or' - If x is True, it returns the value of x; otherwise, it returns the computed value of y": 'x or y 布尔"或" - 如果 x 是 True，它返回 x 的值，否则它返回 y 的计算值',
    "not x boolean 'not' - If x is True, returns False. If x is False, it returns True": 'not x 布尔"非" - 如果 x 为 True，返回 False  .如果 x 为 False，它返回 True',
    "Grid, None if the object is not a mesh": '网格,如果物体不为mesh则为None',
    "parameter": '参数',
    "Set keybinding mapping": '设置键位映射',
    "set direction": '设置方向',
    "Reset the shortcuts": '重置快捷键',
    "No gestures available, please add one": '暂无手势,请添加',
    "Select All": '选择所有',
    "Import gestures": '导入手势',
    "Import presets": '导入预设',
    "Export gestures": '导出手势',
    "No export items selected": '未选择导出项',
    "Export completed": '导出完成',
    "switch mode": '切换模式',
    "author": '作者',
    "Toggle object mode": '切换物体模式',
    "Toggle object edit mode": '切换物体编辑模式',
}
